### ISSUE TITLE
bamCoverage memory in scRNAseq

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#284]
This is still using 8GB of RAM, when we need to reserve more (likely 20GB)

**Comment by dpryan79** [comment]
`shared/cluster.yaml` can be updated to:

```
bamCoverage:
    memory: 4G
bamCoverage_RPKM:
    memory: 4G
bamCoverage_coverage:
    memory: 4G
bamCoverage_raw:
    memory: 4G
```
