### ISSUE TITLE
ChIP-seq 2.0.1: mapping values are not allowed here

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#597]
```bash
DNA-mapping -i $PWD/preprocessing/mergedFASTQ -o $PWD/DNA-mapping --trim --fastqc --plotFormat pdf --dedup --mapq 3 --verbose --jobs 80 --local GRCm38_M24_basic

ChIP-seq -d $PWD/DNA-mapping --singleEnd  --plotFormat pdf --local --verbose --jobs 40 GRCm38_M24_basic $PWD/sampleSheet.yaml
```
Could this be due to a wrongly formatted sample sheet? 

Sample sheet example:
[sampleSheet.yaml](https://github.com/maxplanck-ie/snakepipes/files/4336488/sampleSheet.txt)

ChIP-seq run log:
[ChIP-seq_run-4.log](https://github.com/maxplanck-ie/snakepipes/files/4336470/ChIP-seq_run-4.txt)

SnakePipes setup:
[00_setup_snakePipes.sh](https://github.com/maxplanck-ie/snakepipes/files/4336472/00_setup_snakePipes.txt)

**Comment by AdrijaK** [comment]
Edit: the sampleSheet.yaml indeed was incorrect: 
1. the sampleSheet has to start with "chip_dict:"
2. the nesting of samples (by mark) is not possible
3. the colon was missing at the end of each sample name. 

This doesnt work:
```
                         # missing "chip_dict:"
H3K27ac:                 # don't nest samples under ChIP mark 
  H3K27ac-veh-rep3       # missing ":"
    broad: False
    control: FA-veh-rep1
  H3K27ac-veh-rep2
    broad: False
    control: FA-veh-rep1
  H3K27ac-veh-rep1
    broad: False
    control: FA-veh-rep1
  H3K27ac-dox-rep3
    broad: False
    control: FA-dox-rep1
  H3K27ac-dox-rep2
    broad: False
    control: FA-dox-rep1
  H3K27ac-dox-rep1
    broad: False
    control: FA-dox-rep1
H3K27me3:
  H3K27me3-veh-rep3
    broad: True
    control: FA-veh-rep1
  H3K27me3-veh-rep2
    broad: True
    control: FA-veh-rep1
  H3K27me3-veh-rep1
    broad: True
    control: FA-veh-rep1
  H3K27me3-dox-rep3
    broad: True
    control: FA-dox-rep1
  H3K27me3-dox-rep2
    broad: True
    control: FA-dox-rep1
  H3K27me3-dox-rep1
    broad: True
    control: FA-dox-rep1
```

This works: 
```
chip_dict:
  H3K27ac-veh-rep3:
    broad: False
    control: FA-veh-rep1
  H3K27ac-veh-rep2:
    broad: False
    control: FA-veh-rep1
  H3K27ac-veh-rep1:
    broad: False
    control: FA-veh-rep1
  H3K27ac-dox-rep3:
    broad: False
    control: FA-dox-rep1
  H3K27ac-dox-rep2:
    broad: False
    control: FA-dox-rep1
  H3K27ac-dox-rep1:
    broad: False
    control: FA-dox-rep1
  H3K27me3-veh-rep3:
    broad: True
    control: FA-veh-rep1
  H3K27me3-veh-rep2:
    broad: True
    control: FA-veh-rep1
  H3K27me3-veh-rep1:
    broad: True
    control: FA-veh-rep1
  H3K27me3-dox-rep3:
    broad: True
    control: FA-dox-rep1
  H3K27me3-dox-rep2:
    broad: True
    control: FA-dox-rep1
  H3K27me3-dox-rep1:
    broad: True
    control: FA-dox-rep1
```
