### ISSUE TITLE
ruamel.yaml vs pyyaml

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/snakepipes#967]
It seems pytests would require the use of ruamel yaml instead of pyyaml (#966) (at least if we want to keep generating all the data 'on the fly'). This seems to be pulled in as a dependency already, though should probably be an explicit dependency.

The 'regular yamls' (i.e. organism, chipdicts, ...) are parsed with pyyaml, but show some inconsistent behavior when being parsed, leading to different number of jobs inferred. This showed up in #965. 

For example:
```
chip_dict:
  sample1:
    control: sample7
    broad: False
```
&
```
chip_dict:
  sample1:
    control: sample7
    broad: "False"
```
Lead to a different number of jobs inferred.

Ideally parsing the yamls are made a bit more robust, and for consistency would also be done with ruamel's yaml.
